### ISSUE TITLE
Any major changes planned?

### ISSUE THREAD

**Issue by homerhanumat** [dt801ts/sublime-hugo-theme#4]
Great theme, @dt801ts!  I'm wondering if you plan major changes or enhancements in the near future.  If not then I plan to fork it and modify it for use with the [**blogdown**](https://github.com/rstudio/blogdown) R-package.

**Comment by dt801ts** [comment]
Hi @homerhanumat, thanks for your kind words. I am not planning any major changes for the near future. @jhabdas has tinkered with reformatting things somewhat for fetch injection, which would speed up loading ... that's the only adjustment I may incorporate soon, if a few kinks can be worked out. I look forward to seeing what you do with R markdown. Best regards.

**Comment by homerhanumat** [comment]
R-bloggers don't need much -- just MathJax and some tags.  Here is what I've got so far:

>[https://homerhanumat.rbind.io](https://homerhanumat.rbind.io)
