### ISSUE TITLE
Please remove the themes folder in exampleSite

### ISSUE THREAD

**Issue by digitalcraftsman** [dt801ts/sublime-hugo-theme#6]
Hello @dt801ts,

it's correct that `exampleSite` mirrors the root folder of a Hugo website. But there's no need to create a `themes` directory in `exampleSite`. `exampleSite/themes/sublime-hugo` is a symbolic link that creates an infnite loop. This causes an error when someone tries to clone the [hugoThemes](https://github.com/gohugoio/hugoThemes) directory.

Hence, please remove the `themes` folder in `exampleSite`.

**Comment by dt801ts** [comment]
Hi @digitalcraftsman ,

I apologize for the late reply. Somehow I'm just seeing this now. I removed the themes directory from exampleSite. Hopefully this resolves the problem, and hopefully my theme can now be put back on Hugo's theme gallery page ? 

Thanks

**Comment by digitalcraftsman** [comment]
Hi @dt801ts.

it looks good now. I've (re)added your theme. It should appear soon on the theme site.

Best,
Digitalcraftsman
